//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocre {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ocre.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested types should be sorted correctly within their containing types..
        /// </summary>
        internal static string NestedTypeOrderDescription {
            get {
                return ResourceManager.GetString("NestedTypeOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested type &apos;{0}&apos; is not ordered correctly within &apos;{1}&apos;. Expected order is: {2}..
        /// </summary>
        internal static string NestedTypeOrderMessageFormat {
            get {
                return ResourceManager.GetString("NestedTypeOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested type is not ordered correctly within its containing type.
        /// </summary>
        internal static string NestedTypeOrderTitle {
            get {
                return ResourceManager.GetString("NestedTypeOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators should be sorted according to the configured operator order..
        /// </summary>
        internal static string OperatorOrderDescription {
            get {
                return ResourceManager.GetString("OperatorOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; is not ordered correctly. Expected operator order is: {1}..
        /// </summary>
        internal static string OperatorOrderMessageFormat {
            get {
                return ResourceManager.GetString("OperatorOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is not ordered correctly.
        /// </summary>
        internal static string OperatorOrderTitle {
            get {
                return ResourceManager.GetString("OperatorOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type members should be sorted correctly within their containing types..
        /// </summary>
        internal static string TypeMemberOrderDescription {
            get {
                return ResourceManager.GetString("TypeMemberOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; in type &apos;{1}&apos; is not ordered correctly. Expected order is: {2}..
        /// </summary>
        internal static string TypeMemberOrderMessageFormat {
            get {
                return ResourceManager.GetString("TypeMemberOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type member is not ordered correctly.
        /// </summary>
        internal static string TypeMemberOrderTitle {
            get {
                return ResourceManager.GetString("TypeMemberOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types should be sorted correctly in the file..
        /// </summary>
        internal static string TypeOrderInFileDescription {
            get {
                return ResourceManager.GetString("TypeOrderInFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not ordered correctly at the file level. Expected order is: {1}..
        /// </summary>
        internal static string TypeOrderInFileMessageFormat {
            get {
                return ResourceManager.GetString("TypeOrderInFileMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not ordered correctly at the file level.
        /// </summary>
        internal static string TypeOrderInFileTitle {
            get {
                return ResourceManager.GetString("TypeOrderInFileTitle", resourceCulture);
            }
        }
    }
}
